In [2]:
!pip install espn_api

Requirement already satisfied: espn_api in /opt/anaconda3/lib/python3.9/site-packages (0.45.1)
Requirement already satisfied: requests<3.0.0,>=2.0.0 in /opt/anaconda3/lib/python3.9/site-packages (from espn_api) (2.31.0)
Requirement already satisfied: urllib3<=2.2.3 in /opt/anaconda3/lib/python3.9/site-packages (from espn_api) (1.26.18)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->espn_api) (2.0.4)
Requirement already satisfied: idna<4,>=2.5 in /opt/anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->espn_api) (3.3)
Requirement already satisfied: certifi>=2017.4.17 in /opt/anaconda3/lib/python3.9/site-packages (from requests<3.0.0,>=2.0.0->espn_api) (2021.10.8)

[notice] A new release of pip is available: 24.1.2 -> 25.2
[notice] To update, run: pip install --upgrade pip

In [3]:
import pandas as pd
import numpy as np
import espn_api as espn
from espn_api.football import League
import matplotlib.pyplot as plt
import seaborn as sns

### Connect to league

In [4]:
import os
# from espn_api.football import League

LEAGUE_ID = 86952922
YEARS = [2021, 2022, 2024]

y = YEARS[-1]

# for y in YEARS[-1:]:
    
espn_s2 = "AEC20e998honXS4Wi0Z8qzlJdam4%2F%2BaApa7apspnhKR0Npb%2FMsF5DuQsFUcHW%2FhPihQun9U6PGITOi2CkbdfDCkUc8druBVhAwT08Lzrvv8oZli8YAuTi9mIWg7YqtorCNOEKPxHpYswnT3q7b885tRDKBJpLCH0T2h4h1p%2B02SfdlDhjEB2gHqFk1xl6tJRNMBiCkZ8i5RttLW6ER9ZvLTmmAdb5ceZhQ27NEMiMf%2BjWSSvwBdnf2roxwt9baw33BVnnITqYVb8FXsaUwm7%2Bm0m9GLQ%2B66%2BU%2Brg%2BQngXm1ekA%3D%3D"
swid = "{B431504E-F779-4C49-B3E8-28DDF7409957}"
kwargs = {"league_id": LEAGUE_ID, "year": y, "swid":swid, "espn_s2":espn_s2}
league = League(**kwargs)
teams_count = len(league.teams) if getattr(league, "teams", None) else None
# Try to read a small bit of data to validate
draft = league.draft

In [5]:
from urllib.parse import unquote
espn_s2 = unquote(espn_s2)
league = League(league_id=LEAGUE_ID, year=y, swid=swid, espn_s2=espn_s2)

### Get historical fantasy stats from Pro Football Reference

In [153]:
import requests
from bs4 import BeautifulSoup, Comment
import pandas as pd
import re

def scrape_pfr_fantasy(year: int) -> pd.DataFrame:
    url = f"https://www.pro-football-reference.com/years/{year}/fantasy.htm"
    headers = {"User-Agent": "Mozilla/5.0"}
    html = requests.get(url, headers=headers).text
    soup = BeautifulSoup(html, "html.parser")

    # Helper: return the fantasy table element whether it's in DOM or inside comments
    def find_fantasy_table(soup: BeautifulSoup):
        # 1) try live
        t = soup.find("table", {"id": "fantasy"})
        if t:
            return t
        # 2) scan comments
        for c in soup.find_all(string=lambda t: isinstance(t, Comment)):
            if 'id="fantasy"' in c:
                frag = BeautifulSoup(c, "html.parser")
                t = frag.find("table", {"id": "fantasy"})
                if t:
                    return t
        return None

    table = find_fantasy_table(soup)
    if table is None:
        raise ValueError(f"Fantasy table not found for {year}")

    # Build column order from the LAST header row in thead (skip over_header rows)
    thead = table.find("thead")
    header_rows = [tr for tr in thead.find_all("tr") if "over_header" not in tr.get("class", [])]
    # last header row is the one with the actual columns
    last_hdr = header_rows[-1]
    cols = []
    for th in last_hdr.find_all("th"):
        key = th.get("data-stat", "").strip()
        if key:  # skip corner blanks
            cols.append(key)

    # Parse body rows using data-stat keys
    data = []
    tbody = table.find("tbody")
    for tr in tbody.find_all("tr"):
        # PFR sometimes repeats a header row inside tbody with class="thead"
        if "thead" in tr.get("class", []):
            continue

        row = {}
        # some tables have a row header in <th scope="row">
        th = tr.find("th", {"scope": "row"})
        if th is not None:
            k = th.get("data-stat", "").strip() or "rk"
            row[k] = th.get_text(strip=True)

        for td in tr.find_all("td"):
            k = td.get("data-stat", "").strip()
            if not k:
                continue
            row[k] = td.get_text(strip=True)

        # skip completely empty rows
        if not row:
            continue
        data.append(row)

    # Create DataFrame and align to column order (keep any extra keys too)
    df = pd.DataFrame(data)

    # Ensure the final column order starts with `cols` then any extras
    extras = [c for c in df.columns if c not in cols]
    df = df[[c for c in cols if c in df.columns] + extras]

    # Clean: remove repeated header rows if any sneaked in
    if "player" in df.columns:
        df = df[df["player"].str.lower() != "player"]

    # Coerce numeric columns
    for c in df.columns:
        if c in ("player", "team", "pos", "tm"):
            continue
        df[c] = pd.to_numeric(df[c], errors="ignore")

    return df

# Example usage
df_2021 = scrape_pfr_fantasy(2020)

In [154]:
pd.set_option('display.max_columns', None)
df_2021.head()

,ranker,player,team,fantasy_pos,age,g,gs,pass_cmp,pass_att,pass_yds,pass_td,pass_int,rush_att,rush_yds,rush_yds_per_att,rush_td,targets,rec,rec_yds,rec_yds_per_rec,rec_td,fumbles,fumbles_lost,all_td,two_pt_md,two_pt_pass,fantasy_points,fantasy_points_ppr,draftkings_points,fanduel_points,vbd,fantasy_rank_pos,fantasy_rank_overall
0,1,Derrick Henry*+,TEN,RB,26,16,16,0,0,0,0,0,378,2027,5.36,17,31,19,114,6.00,0,3.0,2,17,1.0,NaN,314.0,333.1,341.1,323.6,184.0,1,1.0
1,2,Alvin Kamara*,NOR,RB,25,15,10,0,0,0,0,0,187,932,4.98,16,107,83,756,9.11,5,1.0,0,21,NaN,NaN,295.0,377.8,383.8,336.3,165.0,2,2.0
2,3,Dalvin Cook*,MIN,RB,25,14,14,0,0,0,0,0,312,1557,4.99,16,54,44,361,8.20,1,5.0,3,17,3.0,NaN,294.0,337.8,346.8,315.8,164.0,3,3.0
3,4,Davante Adams*+,GNB,WR,28,14,14,0,0,0,0,0,0,0,NaN,0,149,115,1374,11.95,18,1.0,1,18,NaN,NaN,243.0,358.4,362.4,300.9,117.0,1,4.0
4,5,Travis Kelce*+,KAN,TE,31,15,15,1,2,4,0,0,0,0,NaN,0,145,105,1416,13.49,11,1.0,1,11,1.0,NaN,208.0,312.8,316.8,260.3,117.0,1,5.0

In [155]:
df_2021['player_name'] = df_2021['player'].str.replace(r"[*+]", "", regex=True).str.strip()
stats = df_2021[['player_name', 'team', 'fantasy_pos', 'g', 'gs', 'fantasy_points_ppr']]
stats = stats.loc[stats['fantasy_pos'].isin(['QB', 'RB', 'WR', 'TE'])]
stats['fantasy_points_ppr'].fillna(0, inplace=True)
stats["pos_rank"] = (
    stats.groupby("fantasy_pos")["fantasy_points_ppr"]
      .rank(method="dense", ascending=False)
      .astype(int)
)

stats["full_rank"] = (
    stats["fantasy_points_ppr"]
      .rank(method="dense", ascending=False)
      .astype(int)
)

In [156]:
stats.sort_values('fantasy_points_ppr', ascending=False).head(20)

,player_name,team,fantasy_pos,g,gs,fantasy_points_ppr,pos_rank,full_rank
6,Josh Allen,BUF,QB,16,16,396.1,1,1
7,Aaron Rodgers,GNB,QB,16,16,383.3,2,2
8,Kyler Murray,ARI,QB,16,16,378.7,3,3
1,Alvin Kamara,NOR,RB,15,10,377.8,1,4
9,Patrick Mahomes,KAN,QB,15,15,374.4,4,5
10,Deshaun Watson,HOU,QB,16,16,369.3,5,6
15,Russell Wilson,SEA,QB,16,16,359.8,6,7
3,Davante Adams,GNB,WR,14,14,358.4,1,8
22,Ryan Tannehill,TEN,QB,16,16,344.4,7,9
25,Tom Brady,TAM,QB,16,16,337.9,8,10
2,Dalvin Cook,MIN,RB,14,14,337.8,2,11
0,Derrick Henry,TEN,RB,16,16,333.1,3,12
29,Justin Herbert,LAC,QB,15,15,332.8,9,13
30,Lamar Jackson,BAL,QB,15,15,332.8,9,13
5,Tyreek Hill,KAN,WR,15,15,328.9,2,14
16,Stefon Diggs,BUF,WR,16,15,328.6,3,15
4,Travis Kelce,KAN,TE,15,15,312.8,1,16
45,Kirk Cousins,MIN,QB,16,16,306.2,10,17
32,DeAndre Hopkins,ARI,WR,16,16,287.8,4,18
74,Matt Ryan,ATL,QB,16,16,282.4,11,19

In [157]:
rates = {'QB':12, 'RB':30, 'WR':30, 'TE':12}

def top_by_position_df(df: pd.DataFrame, rates: dict):
    # expect columns: position, pos_rank, overall_rank (case-insensitive ok)
    df2 = df.copy()
    df2["fantasy_pos"] = df2["fantasy_pos"].str.upper()

    frames = []
    for pos, n in rates.items():
        g = df2[df2["fantasy_pos"] == pos].sort_values(
            by=["pos_rank", "full_rank"],
            na_position="last"
        ).head(n)
        frames.append(g)

    out = pd.concat(frames, ignore_index=True) if frames else df2.iloc[0:0]
    # also return a flat list ordered by overall_rank if you want
    flat = out.sort_values(by=["full_rank"], na_position="last")
    return out, flat


by_pos_df, flat_df = top_by_position_df(stats, rates)

In [158]:
flat_df.head(20)

,player_name,team,fantasy_pos,g,gs,fantasy_points_ppr,pos_rank,full_rank
0,Josh Allen,BUF,QB,16,16,396.1,1,1
1,Aaron Rodgers,GNB,QB,16,16,383.3,2,2
2,Kyler Murray,ARI,QB,16,16,378.7,3,3
12,Alvin Kamara,NOR,RB,15,10,377.8,1,4
3,Patrick Mahomes,KAN,QB,15,15,374.4,4,5
4,Deshaun Watson,HOU,QB,16,16,369.3,5,6
5,Russell Wilson,SEA,QB,16,16,359.8,6,7
42,Davante Adams,GNB,WR,14,14,358.4,1,8
6,Ryan Tannehill,TEN,QB,16,16,344.4,7,9
7,Tom Brady,TAM,QB,16,16,337.9,8,10
13,Dalvin Cook,MIN,RB,14,14,337.8,2,11
14,Derrick Henry,TEN,RB,16,16,333.1,3,12
8,Justin Herbert,LAC,QB,15,15,332.8,9,13
9,Lamar Jackson,BAL,QB,15,15,332.8,9,13
43,Tyreek Hill,KAN,WR,15,15,328.9,2,14
44,Stefon Diggs,BUF,WR,16,15,328.6,3,15
72,Travis Kelce,KAN,TE,15,15,312.8,1,16
10,Kirk Cousins,MIN,QB,16,16,306.2,10,17
45,DeAndre Hopkins,ARI,WR,16,16,287.8,4,18
11,Matt Ryan,ATL,QB,16,16,282.4,11,19

### Create Draft Value Metric

In [161]:
def compute_vorp_star(
    df: pd.DataFrame,
    teams: int = 12,
    starters_per_team: dict = None,
    use_ppg: bool = False,
    min_games_for_ppg: int = 8,
    pool_factor: float = 2.0,         # pool ~ 2× starters per position
    winsor_limits: tuple = (0.02, 0.98)  # clamp extremes for robust scale
):
    """
    Returns a copy of df with columns:
      - points_used         (PPG or season total)
      - rep_points          (replacement level for the position)
      - vorp_raw            (points_used - rep_points)
      - pos_scale_robust    (1.4826 * MAD of (points_used - rep_points) in pool)
      - vorp_star           (vorp_raw / pos_scale_robust)
      - injury_flag         (True if < min_games_for_ppg when use_ppg)
    """

    df = df.copy()

    # 1) Decide points metric (total or PPG)
    if use_ppg:
        df["points_used"] = df["fantasy_points_ppr"] / df["g"].replace(0, np.nan)
        # flag small-sample seasons
        df["injury_flag"] = (df["g"] < min_games_for_ppg) | (~np.isfinite(df["points_used"]))
    else:
        df["points_used"] = df["fantasy_points_ppr"]
        df["injury_flag"] = False

    # Fill any NaNs created (e.g., 0 games) with 0 so later math works;
    # they’ll still be flagged as injury_flag=True if use_ppg
    df["points_used"] = df["points_used"].fillna(0.0)

    # 2) Replacement level per position
    # Default lineup for 12-team, 1QB/2RB/2WR/1TE (adjust if your league differs)
    if starters_per_team is None:
        starters_per_team = {"QB": 1, "RB": 2.5, "WR": 2.5, "TE": 1}

    # How many starters in the league per position = teams * starters_per_team[pos]
    rep_index = {
        pos: int(teams * starters_per_team.get(pos, 0))
        for pos in df["fantasy_pos"].unique()
    }
    
    # Helper: robust MAD scale
    def mad(x):
        med = np.median(x)
        return 1.4826 * np.median(np.abs(x - med))

    # Helper: winsorize
    def winsorize(s, lo=0.02, hi=0.98):
        ql, qh = np.quantile(s, [lo, hi])
        return np.clip(s, ql, qh)

    out_frames = []
    for pos, grp in df.groupby("fantasy_pos", sort=False):
        # sort high→low by points_used
        gsort = grp.sort_values("points_used", ascending=False)

        # replacement rank (e.g., RB24). If none defined, skip normalization gracefully.
        # R = rep_index.get(pos, 0)
        # if R <= 0 or R > len(gsort):
        #     # no valid replacement index; fall back to zero baseline/scale=1 to avoid div-by-0
        #     rep_points = 0.0
        # else:
        #     rep_points = gsort.iloc[R-1]["points_used"]
        
    
        R = rep_index.get(pos, 0)
        if R <= 0 or R > len(gsort):
            rep_points = 0.0
        else:
            rep_points = gsort.iloc[R-1]["points_used"]


        gsort = gsort.assign(rep_points=rep_points)
        gsort = gsort.assign(vorp_raw=gsort["points_used"] - rep_points)

        # build pool ~ top (pool_factor × starters) to estimate robust spread
        pool_size = int(max(R * pool_factor, min(len(gsort), R))) if R > 0 else min(len(gsort), 24)
        pool = gsort.iloc[:pool_size]["vorp_raw"].values

        # winsorize pool then MAD
        pool_w = winsorize(pool, *winsor_limits) if len(pool) else np.array([0.0])
        scale = np.std(pool_w, ddof=0)   # population std dev
        if scale == 0 or not np.isfinite(scale):
            scale = 1.0   # avoid divide by 0

        gsort = gsort.assign(pos_scale_robust=scale)
        gsort = gsort.assign(vorp_star=gsort["vorp_raw"] / scale)

        out_frames.append(gsort)

    result = pd.concat(out_frames, axis=0).sort_index()

    # Optional: ranks
    result["vorp_star_rank_overall"] = result["vorp_star"].rank(method="dense", ascending=False).astype(int)
    result["vorp_star_rank_pos"] = (
        result.groupby("fantasy_pos")["vorp_star"].rank(method="dense", ascending=False).astype(int)
    )

    return result

# -------------------------
# Example usage on your df:
# -------------------------
# df has: player_name, team, fantasy_pos, g, gs, fantasy_points_ppr, pos_rank, full_rank

# Example for 12-team, 1QB/2RB/2WR/1TE, using season totals:
df_v = compute_vorp_star(
    stats,
    teams=12,
    starters_per_team={"QB": 1.25, "RB": 2.5, "WR": 2.5, "TE": 1.25},
    use_ppg=False,           # set True if you prefer per-game
    min_games_for_ppg=8,
    pool_factor=1,
    winsor_limits=(0.02, 0.98),
)

# Columns now available:
# ['points_used','rep_points','vorp_raw','pos_scale_robust','vorp_star',
#  'injury_flag','vorp_star_rank_overall','vorp_star_rank_pos', ...]
# Example view:
cols = [
    "player_name","team","fantasy_pos","fantasy_points_ppr","vorp_star","vorp_star_rank_overall", "vorp_star_rank_pos"
]
df_v[cols].sort_values(["vorp_star"], ascending=False).head(30)

,player_name,team,fantasy_pos,fantasy_points_ppr,vorp_star,vorp_star_rank_overall,vorp_star_rank_pos
3,Davante Adams,GNB,WR,358.4,4.284542,1,1
1,Alvin Kamara,NOR,RB,377.8,4.193523,2,1
4,Travis Kelce,KAN,TE,312.8,3.616856,3,1
5,Tyreek Hill,KAN,WR,328.9,3.527692,4,2
16,Stefon Diggs,BUF,WR,328.6,3.519995,5,3
2,Dalvin Cook,MIN,RB,337.8,3.430023,6,2
0,Derrick Henry,TEN,RB,333.1,3.340312,7,3
6,Josh Allen,BUF,QB,396.1,3.109318,8,1
14,Darren Waller,LVR,TE,278.6,2.893485,9,2
7,Aaron Rodgers,GNB,QB,383.3,2.814727,10,2
8,Kyler Murray,ARI,QB,378.7,2.708858,11,3
9,Patrick Mahomes,KAN,QB,374.4,2.609894,12,4
10,Deshaun Watson,HOU,QB,369.3,2.492518,13,5
32,DeAndre Hopkins,ARI,WR,287.8,2.473233,14,4
19,Calvin Ridley,ATL,WR,281.5,2.311600,15,5
15,Russell Wilson,SEA,QB,359.8,2.273876,16,6
23,Justin Jefferson,MIN,WR,274.2,2.124312,17,6
21,D.K. Metcalf,SEA,WR,271.3,2.049910,18,7
13,David Montgomery,CHI,RB,264.8,2.036636,19,4
12,Aaron Jones,GNB,RB,258.9,1.924020,20,5
22,Ryan Tannehill,TEN,QB,344.4,1.919446,21,7
34,Tyler Lockett,SEA,WR,265.4,1.898540,22,8
38,Allen Robinson,CHI,WR,262.9,1.834400,23,9
11,Jonathan Taylor,IND,RB,252.8,1.807586,24,6
25,Tom Brady,TAM,QB,337.9,1.769849,25,8
17,James Robinson,JAX,RB,250.4,1.761776,26,7
29,Justin Herbert,LAC,QB,332.8,1.652472,27,9
30,Lamar Jackson,BAL,QB,332.8,1.652472,27,9
26,Adam Thielen,MIN,WR,254.0,1.606062,28,10
27,Mike Evans,TAM,WR,248.6,1.467520,29,11

In [160]:
df_v.loc[df_v.player_name == 'Marquise Brown']

,player_name,team,fantasy_pos,g,gs,fantasy_points_ppr,pos_rank,full_rank,points_used,injury_flag,rep_points,vorp_raw,pos_scale_robust,vorp_star,vorp_star_rank_overall,vorp_star_rank_pos
102,Marquise Brown,BAL,WR,16,14,183.0,35,74,183.0,False,191.4,-8.4,38.977325,-0.21551,92,35

In [189]:
for year in [2022, 2024]:
    kwargs = {"league_id": LEAGUE_ID, "year": year, "swid":swid, "espn_s2":espn_s2}
    league = League(**kwargs)

    for team in league.teams:
        print(team.team_id, team.team_name)

1 RAWDOGS ®
2 ROTC JARHEAD
3 Monica  Lazynski
4 Team E Brenner
5 The “Mecca” Daddy satty
6 Big Daddy Bones
7 Brxggzy Bunch
8 Team Brenner
9 Big  Booty Squad
10 Team Jeev
11 gym shorts boner
12 Team ODAWG
13 Beanshootah No leave
14 TURN DOWN FOR WATT
1 RAWDOGS ®
2 MARSHA NH
3 The Didler
4 Team E Brenner
5 The “Mecca” Daddy satty
6 Faid XE
7 Brxggzy Bunch
8 Team Brenner
9 Tony Muscles
10 Team Jeev
12 The Reptilians
14 TURN DOWN FOR WATT

# Trades

In [63]:
from collections import defaultdict
from espn_api.football import League

# ---- setup your League as usual ----
# league = League(league_id=..., year=..., espn_s2="...", swid="...")

def guess_max_week(league):
    # Use any team's scores length as an upper bound (includes playoffs)
    teams = league.teams
    if not teams:
        return 17
    return max(len(t.scores) for t in teams) or 17

def get_team_map(league):
    return {t.team_id: t.team_name for t in league.teams}

def get_weekly_rosters(league, week):
    """
    Returns:
      roster_by_team: dict[team_id] -> set[playerId]
      player_meta: dict[playerId] -> {'name': str}
      team_meta: dict[team_id] -> {'name': str}
    """
    roster_by_team = defaultdict(set)
    player_meta = {}
    team_meta = get_team_map(league)

    try:
        box_scores = league.box_scores(week=week)
    except Exception:
        return {}, {}, team_meta

    for box in box_scores:
        for side in ("home", "away"):
            team = getattr(box, f"{side}_team", None)
            lineup = getattr(box, f"{side}_lineup", []) or []

            if team is None:
                continue
            
            
            
            if type(team) != int:
                tid = team.team_id
            for p in lineup:
                pid = getattr(p, "playerId", None)
                if pid is None:
                    continue
                roster_by_team[tid].add(pid)
                # Cache simple player metadata for printing later
                if pid not in player_meta:
                    player_meta[pid] = {"name": getattr(p, "name", f"Player {pid}")}

    return roster_by_team, player_meta, {tid: {"name": name} for tid, name in team_meta.items()}

def build_ownership_timeseries(league, weeks):
    """
    Returns:
      owner_by_player: dict[playerId] -> dict[week] -> team_id (or None if not rostered we didn’t see them)
      player_meta, team_meta
    """
    owner_by_player = defaultdict(dict)
    player_meta_all = {}
    team_meta = get_team_map(league)

    for wk in weeks:
        r_by_team, player_meta, _team_meta = get_weekly_rosters(league, wk)
        # merge player meta
        for k, v in player_meta.items():
            if k not in player_meta_all:
                player_meta_all[k] = v

        # invert to player->team
        for tid, pset in r_by_team.items():
            for pid in pset:
                owner_by_player[pid][wk] = tid

        # ensure all seen teams present even if empty (not strictly necessary)
        _ = _team_meta  # kept for symmetry; team names already loaded

    return owner_by_player, player_meta_all, {tid: {"name": name} for tid, name in team_meta.items()}

def detect_transfers(owner_by_player, weeks):
    """
    Returns list of dicts:
     {'week': int, 'playerId': int, 'from_team': int, 'to_team': int}
    """
    week_list = sorted(weeks)
    changes = []
    for pid, w2owner in owner_by_player.items():
        last_team = None
        for w in week_list:
            team = w2owner.get(w, None)
            if last_team is None:
                last_team = team
                continue
            if team != last_team:
                # only flag if both sides are not None (ignore FA/unknown -> team)
                if last_team is not None and team is not None:
                    changes.append({
                        "week": w,
                        "playerId": pid,
                        "from_team": last_team,
                        "to_team": team,
                    })
                last_team = team
    return changes

def cluster_trades(changes, min_players_total=2):
    """
    Group changes by week and team pair; classify candidate packages.
    Returns dict:
      week -> list of packages, each:
        {
          'teams': (a, b),             # team_ids sorted
          'a_to_b': [playerId, ...],
          'b_to_a': [playerId, ...],
          'is_trade_like': bool
        }
    """
    by_week_pair = defaultdict(lambda: defaultdict(lambda: {"a_to_b": [], "b_to_a": []}))

    for ch in changes:
        w = ch["week"]
        a, b = ch["from_team"], ch["to_team"]
        if a == b:
            continue
        pair = tuple(sorted((a, b)))
        # Normalize direction with respect to sorted pair
        if (a, b) == pair:
            by_week_pair[w][pair]["a_to_b"].append(ch["playerId"])
        else:
            by_week_pair[w][pair]["b_to_a"].append(ch["playerId"])

    # finalize + classify
    result = defaultdict(list)
    for w, pairs in by_week_pair.items():
        for pair, payload in pairs.items():
            a_to_b = payload["a_to_b"]
            b_to_a = payload["b_to_a"]
            is_trade_like = (len(a_to_b) > 0 and len(b_to_a) > 0) or (len(a_to_b) + len(b_to_a) >= min_players_total)
            result[w].append({
                "teams": pair,
                "a_to_b": a_to_b,
                "b_to_a": b_to_a,
                "is_trade_like": is_trade_like
            })
    return result

def pretty_print_packages(packages_by_week, player_meta, team_meta):
    for w in sorted(packages_by_week.keys()):
        print(f"\n=== Week {w} ===")
        for pkg in packages_by_week[w]:
            a, b = pkg["teams"]
            a_name = team_meta.get(a, {}).get("name", f"Team {a}")
            b_name = team_meta.get(b, {}).get("name", f"Team {b}")

            a_to_b_names = [player_meta.get(pid, {}).get("name", str(pid)) for pid in pkg["a_to_b"]]
            b_to_a_names = [player_meta.get(pid, {}).get("name", str(pid)) for pid in pkg["b_to_a"]]

            tag = "TRADE-LIKE" if pkg["is_trade_like"] else "one-way move"
            print(f"{tag}: {a_name} ↔ {b_name}")
            if a_to_b_names:
                print(f"  {a_name} → {b_name}: {', '.join(a_to_b_names)}")
            if b_to_a_names:
                print(f"  {b_name} → {a_name}: {', '.join(b_to_a_names)}")

# ---- run it ----
def infer_trades(league, start_week=1, end_week=None):
    if end_week is None:
        end_week = guess_max_week(league)

    weeks = range(start_week, end_week + 1)

    owner_by_player, player_meta, team_meta = build_ownership_timeseries(league, weeks)
    changes = detect_transfers(owner_by_player, weeks)
    packages_by_week = cluster_trades(changes, min_players_total=2)

    pretty_print_packages(packages_by_week, player_meta, team_meta)
    return packages_by_week, player_meta, team_meta

# Example:
def build_trade_dataframe(league, start_week=1, end_week=None, only_trade_like=False):
    """
    Returns a pandas DataFrame with one row per detected ownership change.
    Columns:
      week, player_id, player_name,
      from_team_id, from_team_name,
      to_team_id, to_team_name,
      trade_like (bool)
    Set only_trade_like=True to keep only symmetric (both directions) moves.
    """
    if end_week is None:
        end_week = guess_max_week(league)
    weeks = range(start_week, end_week + 1)

    # reuse prior pipeline
    owner_by_player, player_meta, team_meta = build_ownership_timeseries(league, weeks)
    changes = detect_transfers(owner_by_player, weeks)
    packages_by_week = cluster_trades(changes, min_players_total=2)

    # fast lookup: (week, fro, to, playerId) -> trade_like?
    trade_like_lookup = {}
    for w, packages in packages_by_week.items():
        for pkg in packages:
            a, b = pkg["teams"]
            tl = pkg["is_trade_like"]
            # players that went a->b
            for pid in pkg["a_to_b"]:
                trade_like_lookup[(w, a, b, pid)] = tl
            # players that went b->a
            for pid in pkg["b_to_a"]:
                trade_like_lookup[(w, b, a, pid)] = tl

    rows = []
    for ch in changes:
        w = ch["week"]
        fro = ch["from_team"]
        to = ch["to_team"]
        pid = ch["playerId"]
        tl = trade_like_lookup.get((w, fro, to, pid), False)

        if only_trade_like and not tl:
            continue

        rows.append({
            "week": w,
            "player_id": pid,
            "player_name": player_meta.get(pid, {}).get("name", str(pid)),
            "from_team_id": fro,
            "from_team_name": team_meta.get(fro, {}).get("name", f"Team {fro}"),
            "to_team_id": to,
            "to_team_name": team_meta.get(to, {}).get("name", f"Team {to}"),
            "trade_like": tl,
        })

    df = pd.DataFrame(rows).sort_values(["week", "player_name"]).reset_index(drop=True)
    return df

# Example usage:
trades = pd.DataFrame()
for year in [2020, 2021, 2022, 2024]:
    league = get_league(year)
    df_trades = build_trade_dataframe(league, start_week=1, end_week=None, only_trade_like=True)
    trades = pd.concat([trades, df_trades])

In [52]:
trades.head()

,week,player_id,player_name,from_team_id,from_team_name,to_team_id,to_team_name,trade_like
0,2,5528,Larry Fitzgerald,7,Team Briggs,6,Big Daddy Bones,True
1,2,15825,Le'Veon Bell,6,Big Daddy Bones,7,Team Briggs,True
2,3,2573079,Carson Wentz,8,Team Brenner,9,HORSECOCK REXY,True
3,3,3043078,Derrick Henry,8,Team Brenner,9,HORSECOCK REXY,True
4,3,2576716,Jamison Crowder,9,HORSECOCK REXY,8,Team Brenner,True

In [53]:
trades.groupby(['from_team_name']).size().sort_values(ascending=False)

from_team_name
The “Mecca” Daddy satty    32
Team Jeev                  26
Big Daddy Bones            24
gym shorts boner           24
mimi top gavin bottom      21
Team Rex                   20
Tony Muscles               16
HORSECOCK REXY             15
Team Briggs                12
Big  Booty Squad            8
RAWDOGS ™                   6
The Reptilians              5
Team ODAWG                  5
TURN DOWN FOR WATT          5
Team  Brxggzy               5
Team E Brenner              4
Team Brenner                4
Team Brenner                4
Greasy  Anal                4
Faid XE                     4
Brxggzy Bunch               4
Mimi Lebrun                 3
Team Ned                    2
The Didler                  2
MARSHA NH                   2
Beanshootah No leave        1
ROTC JARHEAD                1
Andover  Harrington         1
dtype: int64

In [ ]:
# Helper functions for league access
def get_league(year: int):
    """Get ESPN league instance for a given year"""
    # from urllib.parse import unquote
    # espn_s2 = unquote(ESPN_S2)
    return League(league_id=LEAGUE_ID, year=year)

def guess_max_week(league):
    """Guess the maximum week for a league"""
    teams = league.teams
    if not teams:
        return 17
    return max(len(t.scores) for t in teams) or 17

# All-time wins lookup for any person
def quick_wins_lookup(person_name):
    """Get all wins for a specific person across all years"""
    years = [2020, 2021, 2022, 2024]
    all_wins = []
    
    for year in years:
        try:
            league = get_league(year)
            max_week = guess_max_week(league)
            # print(max_week)
            
            for week in range(1, max_week + 1):
                try:
                    box_scores = league.box_scores(week=week)
                    for box in box_scores:
                        if box.is_playoff == False:
                            if type(box) != int:
                                if box.home_score > box.away_score:
                                    # print(box.home_team.team_name, box.away_team.team_name)
                                    if box.home_team.team_name == person_name:
                                        all_wins.append(f"{year} Week {week}: Beat {box.away_team.team_name} ({box.home_score}-{box.away_score})")
                                elif box.away_score > box.home_score:
                                    if box.away_team.team_name == person_name:
                                        all_wins.append(f"{year} Week {week}: Beat {box.home_team.team_name} ({box.away_score}-{box.home_score})")
                                else:
                                    print(year, week, box.home_team.team_name, box.away_team.team_name)
                except Exception as e:
                    print(e)
        except Exception as e:
            print(e)
    
    return all_wins

def get_all_time_wins_summary(person_name):
    """Get detailed wins summary for a person"""
    wins = quick_wins_lookup(person_name)
    
    if not wins:
        print(f"No wins found for {person_name}")
        return
    
    print(f"All-time wins for {person_name}:")
    print(f"Total wins: {len(wins)}")
    print("\nDetailed win list:")
    for win in wins:
    
    # Extract opponents and count wins against each
    opponents = []
    for win in wins:
        # Extract opponent name from the win string
        opponent = win.split("Beat ")[1].split(" (")[0]
        opponents.append(opponent)
    
    # print(f"\nWins by opponent:")
    # opponent_counts = pd.Series(opponents).value_counts()
    # for opponent, count in opponent_counts.items():
    #     print(f"  {opponent}: {count} wins")

# Usage examples:
# quick_wins_lookup("Tony Muscles")
get_all_time_wins_summary("The “Mecca” Daddy satty")

16
17
17
17
All-time wins for The “Mecca” Daddy satty:
Total wins: 15

Detailed win list:
2020 Week 1: Beat Team Briggs (140.06-129.96)
2020 Week 5: Beat Andover  Harrington  (135.86-95.3)
2020 Week 7: Beat Greasy  Anal  (100.62-91.9)
2020 Week 8: Beat Team Ned (132.24-86.78)
2020 Week 9: Beat Team Brenner (87.5-62.46)
2022 Week 2: Beat ROTC JARHEAD (112.32-96.56)
2022 Week 3: Beat RAWDOGS ® (136.6-93.78)
2022 Week 8: Beat Brxggzy Bunch (98.38-95.32)
2022 Week 11: Beat Beanshootah No leave (115.6-93.88)
2024 Week 3: Beat Tony Muscles (129.32-106.38)
2024 Week 5: Beat The Reptilians  (113.14-85.62)
2024 Week 8: Beat MARSHA NH (127.22-111.26)
2024 Week 9: Beat TURN DOWN FOR WATT (127.88-69.32)
2024 Week 10: Beat Team Brenner  (122.0-104.46)
2024 Week 12: Beat Faid XE (135.96-87.46)

In [ ]:
def get_trades_per_person(year):
    """
    Get a dataframe showing the number of trades per person for a given year.
    Each trade is counted once per person (since trades are mutual agreements).
    Groups by team_id to handle team name changes over time.
    Excludes "Team Ned" from all calculations.
    
    Args:
        year (int): The year to analyze
        
    Returns:
        pd.DataFrame: DataFrame with columns ['team_id', 'team_name', 'num_trades']
    """
    try:
        league = get_league(year)
        trade_df = build_trade_dataframe(league, start_week=1, end_week=None, only_trade_like=True)
        
        if trade_df.empty:
            return pd.DataFrame(columns=['team_id', 'team_name', 'num_trades'])
        
        # Remove "Team Ned" from all calculations
        trade_df = trade_df[
            (trade_df['from_team_name'] != 'Team Ned') & 
            (trade_df['to_team_name'] != 'Team Ned')
        ].copy()
        
        if trade_df.empty:
            return pd.DataFrame(columns=['team_id', 'team_name', 'num_trades'])
        
        # Count unique trades per team_id
        # Since each trade involves two people, we need to count unique trade combinations
        trade_combinations = trade_df.groupby(['week', 'from_team_id', 'to_team_id']).size().reset_index()
        
        # Count trades for each team_id (both as sender and receiver)
        trades_count = {}
        
        for _, row in trade_combinations.iterrows():
            from_team_id = row['from_team_id']
            to_team_id = row['to_team_id']
            
            # Count this trade for both participants
            trades_count[from_team_id] = trades_count.get(from_team_id, 0) + 1
            trades_count[to_team_id] = trades_count.get(to_team_id, 0) + 1
        
        # Create mapping from team_id to latest team_name
        team_name_map = {}
        for _, row in trade_df.iterrows():
            team_id = row['from_team_id']
            team_name = row['from_team_name']
            if team_id not in team_name_map:
                team_name_map[team_id] = team_name
            else:
                # Keep the latest name (this handles name changes over time)
                team_name_map[team_id] = team_name
            
            team_id = row['to_team_id']
            team_name = row['to_team_name']
            if team_id not in team_name_map:
                team_name_map[team_id] = team_name
            else:
                team_name_map[team_id] = team_name
        
        # Convert to DataFrame with team_id and latest team_name
        result_data = []
        for team_id, count in trades_count.items():
            result_data.append({
                'team_id': team_id,
                'team_name': team_name_map.get(team_id, f'Team {team_id}'),
                'num_trades': count
            })
        
        result_df = pd.DataFrame(result_data)
        result_df = result_df.sort_values('num_trades', ascending=False).reset_index(drop=True)
        
        return result_df
        
    except Exception as e:
        print(f"Error analyzing trades for {year}: {e}")
        return pd.DataFrame(columns=['team_id', 'team_name', 'num_trades'])

trades = pd.DataFrame()
for year in [2020, 2021, 2022, 2024]:
    temp = get_trades_per_person(year)
    trades = pd.concat([trades, temp])

In [98]:
def build_trades_dataframe(league, start_week=1, end_week=None, only_trade_like=True):
    """
    Returns a pandas DataFrame with one row per trade (not per player).
    Columns:
      week, team1_id, team1_name, team2_id, team2_name,
      team1_players_sent, team1_players_received, team2_players_sent, team2_players_received,
      total_players_traded, is_trade_like
    """
    if end_week is None:
        end_week = guess_max_week(league)
    weeks = range(start_week, end_week + 1)

    # reuse prior pipeline
    owner_by_player, player_meta, team_meta = build_ownership_timeseries(league, weeks)
    changes = detect_transfers(owner_by_player, weeks)
    packages_by_week = cluster_trades(changes, min_players_total=2)

    rows = []
    for week, packages in packages_by_week.items():
        for pkg in packages:
            team1_id, team2_id = pkg["teams"]
            team1_name = team_meta.get(team1_id, {}).get("name", f"Team {team1_id}")
            team2_name = team_meta.get(team2_id, {}).get("name", f"Team {team2_id}")
            
            # Get player names for each direction
            team1_players_sent = [player_meta.get(pid, {}).get("name", str(pid)) for pid in pkg["a_to_b"]]
            team2_players_sent = [player_meta.get(pid, {}).get("name", str(pid)) for pid in pkg["b_to_a"]]
            
            # Determine which team is which based on the sorted pair
            if (team1_id, team2_id) == pkg["teams"]:
                # team1_id is the first in sorted pair, so they sent a_to_b players
                team1_players_received = team2_players_sent
                team2_players_received = team1_players_sent
            else:
                # team1_id is the second in sorted pair, so they sent b_to_a players  
                team1_players_received = team1_players_sent
                team2_players_received = team2_players_sent
                team1_players_sent = team2_players_sent
                team2_players_sent = team1_players_received
            
            total_players = len(pkg["a_to_b"]) + len(pkg["b_to_a"])
            
            # Skip if only_trade_like is True and this isn't trade-like
            if only_trade_like and not pkg["is_trade_like"]:
                continue
            
            rows.append({
                "week": week,
                "team1_id": team1_id,
                "team1_name": team1_name,
                "team2_id": team2_id, 
                "team2_name": team2_name,
                "team1_players_sent": ", ".join(team1_players_sent) if team1_players_sent else "None",
                "team1_players_received": ", ".join(team1_players_received) if team1_players_received else "None",
                "team2_players_sent": ", ".join(team2_players_sent) if team2_players_sent else "None", 
                "team2_players_received": ", ".join(team2_players_received) if team2_players_received else "None",
                "total_players_traded": total_players,
                "is_trade_like": pkg["is_trade_like"]
            })

    df = pd.DataFrame(rows).sort_values(["week", "team1_name"]).reset_index(drop=True)
    return df

# Test the function
# print("Trades by trade (not by player) for 2024:")
full_trades = pd.DataFrame()
for year in [2020, 2021, 2022, 2024]:
    league = get_league(year)
    trades_by_trade = build_trades_dataframe(league, start_week=1, end_week=None, only_trade_like=True)
    trades_by_trade['year'] = year
    full_trades = pd.concat([full_trades, trades_by_trade])

In [116]:
full_trades = full_trades.loc[(full_trades['team1_name'] != 'Team Ned') | (full_trades['team2_name'] != 'Team Ned')]

In [117]:
def get_trade_summary_by_team_id(trades_df):
    """
    Get a summary of trades per team, grouped by team_id to handle name changes.
    """
    team_trades = get_trades_by_team(trades_df)
    
    # Group by team_id and get the latest team_name for each team_id
    summary = team_trades.groupby('team_id').agg({
        'team_name': 'last',  # Get the latest team name
        'week': 'count',  # number of trades
        'total_players_traded': 'sum',  # total players traded
        'is_trade_like': 'sum'  # number of trade-like transactions
    }).reset_index()
    
    summary.columns = ['team_id', 'team_name', 'num_trades', 'total_players_traded', 'trade_like_count']
    summary = summary.sort_values('num_trades', ascending=False).reset_index(drop=True)
    
    return summary

def get_trades_by_team_id(trades_df):
    """
    Get trades by team, using team_id for grouping but showing latest team_name.
    """
    team_trades = get_trades_by_team(trades_df)
    
    # Get the latest team name for each team_id
    latest_names = team_trades.groupby('team_id')['team_name'].last().to_dict()
    
    # Update team names to latest version
    team_trades['team_name'] = team_trades['team_id'].map(latest_names)
    team_trades['traded_with_name'] = team_trades['traded_with_id'].map(latest_names)
    
    return team_trades.sort_values(['team_name', 'week']).reset_index(drop=True)

# Test the updated functions
# print("=== Trade Summary by Team ID (handles name changes) ===")
trade_summary_by_id = get_trade_summary_by_team_id(full_trades)
# print(trade_summary_by_id)

# print("\n=== Trades by Team ID (with latest names) ===")
trades_by_team_id = get_trades_by_team_id(full_trades)
# print(trades_by_team_id.head(10))  # Show first 10 rows

In [ ]:
for _, row in trades_by_team_id.iterrows():
    if row['team_name'] == 'Team E Brenner':
        print(f"Traded with {row['traded_with_name']} on week {row['week']}")

,week,team_id,team_name,traded_with_id,traded_with_name,players_sent,players_received,total_players_traded,is_trade_like
53,6,4,Team E Brenner,7,Team Briggs,"CeeDee Lamb, Jonathan Taylor","Chris Carson, Stefon Diggs, Julio Jones",5,True
54,11,4,Team E Brenner,11,mimi top gavin bottom,James Conner,Terry McLaurin,2,True
55,13,4,Team E Brenner,9,Tony Muscles,Diontae Johnson,"Damien Harris, Amari Cooper, Elijah Mitchell",4,True

In [130]:
combos = trades_by_team_id.groupby(['team_name', 'traded_with_name'], as_index=False).size().sort_values(by='size', ascending=False).iloc[::2]

In [133]:
combos

                  team_name         traded_with_name  size
65             Tony Muscles  The “Mecca” Daddy satty     8
60             Tony Muscles              Team Briggs     5
54  The “Mecca” Daddy satty    mimi top gavin bottom     5
67    mimi top gavin bottom                  Faid XE     4
62             Tony Muscles                Team Jeev     4
39                Team Jeev              Team Briggs     3
17             ROTC JARHEAD             Tony Muscles     3
30              Team Briggs                Team Jeev     3
75    mimi top gavin bottom             Tony Muscles     3
72    mimi top gavin bottom                Team Jeev     3
69    mimi top gavin bottom             ROTC JARHEAD     3
42                Team Jeev    mimi top gavin bottom     3
55             Tony Muscles                  Faid XE     2
5                   Faid XE          The Reptilians      2
36                Team Jeev                  Faid XE     2
64             Tony Muscles          The Reptilians      2
59             Tony Muscles            Team Brenner      2
46          The Reptilians                   Faid XE     2
61             Tony Muscles           Team E Brenner     1
56             Tony Muscles                RAWDOGS ™     1
63             Tony Muscles              The Didler      1
70    mimi top gavin bottom            Team Brenner      1
47          The Reptilians        TURN DOWN FOR WATT     1
45              The Didler              Tony Muscles     1
2                   Faid XE              Team Briggs     1
9                 RAWDOGS ™             ROTC JARHEAD     1
11                RAWDOGS ™                Team Jeev     1
13                RAWDOGS ™    mimi top gavin bottom     1
15             ROTC JARHEAD              Team Briggs     1
19       TURN DOWN FOR WATT          The Reptilians      1
21            Team Brenner               Team Briggs     1
24            Team Brenner     mimi top gavin bottom     1
26              Team Briggs                RAWDOGS ™     1
28              Team Briggs            Team Brenner      1
33           Team E Brenner              Team Briggs     1
35           Team E Brenner    mimi top gavin bottom     1
1                   Faid XE     Beanshootah No leave     1
43              The Didler                   Faid XE     1

# Monte Carlo WPA War

In [ ]:
from dataclasses import dataclass
from typing import Dict, List, Tuple, Optional
from collections import defaultdict

def collect_weekly_points(years):
    rows = []
    matchups = []  # <-- NEW
    for yr in years:
        lg = get_league(yr)
        max_week = 14
        for wk in range(1, max_week + 1):
            for box in lg.box_scores(week=wk):
                # record matchup info
                matchups.append({
                    "year": yr, "week": wk,
                    "home_id": box.home_team.team_id,
                    "away_id": box.away_team.team_id,
                    "home_score": box.home_score,
                    "away_score": box.away_score
                })
                # record player info (same as before)
                for side in ("home_lineup", "away_lineup"):
                    for p in getattr(box, side, []) or []:
                        rows.append({
                            "year": yr,
                            "week": wk,
                            "team_id": getattr(getattr(box, "home_team" if side=="home_lineup" else "away_team"), "team_id", None),
                            "player_id": getattr(p, "playerId", None),
                            "player_name": getattr(p, "name", None),
                            "position": getattr(p, "position", None),
                            "slot": getattr(p, "slot_position", None),
                            "points": getattr(p, "points", None),
                            "proj": getattr(p, "projected_points", None),
                            "is_starter": getattr(p, "slot_position", "") not in ("BE", "IR")
                        })
    return pd.DataFrame(rows), pd.DataFrame(matchups)


def calculate_historical_wpa(weekly_df: pd.DataFrame,
                             replacement_depth: Dict[str, int] = None,
                             max_week: int = 14) -> pd.DataFrame:
    """
    Calculate historical Win Probability Added (WPA) for all players, league-wide.
    Uses actual scores instead of projections (team-independent).
    
    Args:
        weekly_df : DataFrame from collect_weekly_points()
            Columns needed: ["year","week","team_id","player_id","player_name",
                             "position","points","is_starter"]
        replacement_depth : dict mapping position -> depth rank considered replacement
            Example: {"QB": 12, "RB": 24, "WR": 36, "TE": 12}
        max_week : how many weeks to evaluate per season (default = 14 for regular season)
    
    Returns:
        DataFrame with one row per player_id:
            ["player_id","player_name","position","games_played","wins_added"]
    """
    if replacement_depth is None:
        replacement_depth = {"QB": 12, "RB": 24, "WR": 36, "TE": 12}

    results = defaultdict(lambda: {"player_name": None, "position": None, "games_played": 0, "wins_added": 0})

    # Loop season by season
    for (yr, wk), wk_df in weekly_df.groupby(["year", "week"]):
        if wk > max_week:
            continue

        # ---- 1. Compute replacement baseline for each position this week ----
        repl_scores = {}
        for pos, depth in replacement_depth.items():
            pos_scores = wk_df.loc[(wk_df["position"] == pos) & (wk_df["is_starter"]), "points"]
            if len(pos_scores) >= depth:
                repl_scores[pos] = pos_scores.sort_values(ascending=False).iloc[depth-1]
            else:
                repl_scores[pos] = pos_scores.median() if len(pos_scores) > 0 else 0.0

        # ---- 2. Group by matchup (home vs away team) ----
        for (home_id, away_id), matchup in wk_df.groupby(["team_id","week"]):  
            # CAREFUL: need actual matchup data. Let's simplify:
            # We'll pull team totals directly from weekly_df.
            pass  # we'll fix this part below




def estimate_sigma_by_pos(weekly_df: pd.DataFrame) -> Dict[str, float]:
    # Use only weeks with both proj and points
    df = weekly_df.dropna(subset=["proj", "points"]).copy()
    df["err"] = df["points"] - df["proj"]
    # Robustness: winsorize 5th–95th pct by position to avoid outliers
    sigmas = {}
    for pos, grp in df.groupby("position"):
        if len(grp) < 30:
            continue
        lo, hi = np.percentile(grp["err"], [5, 95])
        trimmed = grp["err"].clip(lo, hi)
        sigmas[pos] = float(trimmed.std(ddof=1)) if trimmed.std(ddof=1) > 0 else 5.0
    # reasonable fallbacks
    return {"QB": sigmas.get("QB", 6.5),
            "RB": sigmas.get("RB", 8.5),
            "WR": sigmas.get("WR", 7.5),
            "TE": sigmas.get("TE", 6.0),
            "K":  sigmas.get("K",  3.5),
            "D/ST": sigmas.get("D/ST", 5.0)}


@dataclass
class Starter:
    player_id: int
    name: str
    position: str
    slot: str        # RB/WR/FLEX/QB/TE/K/DST
    proj: float      # ESPN weekly projection

def get_lineup_for_week(league: League, team_id: int, week: int) -> Tuple[List[Starter], List[Starter]]:
    """
    Returns (starters, bench) for the specified team & week based on the box score lineup.
    """
    starters, bench = [], []
    for box in league.box_scores(week=week):
        for side, team_attr, lineup_attr in [("home", "home_team", "home_lineup"), ("away", "away_team", "away_lineup")]:
            team = getattr(box, team_attr)
            if team.team_id != team_id:
                continue
            lineup = getattr(box, lineup_attr) or []
            for p in lineup:
                s = Starter(
                    player_id = getattr(p, "playerId", None),
                    name      = getattr(p, "name", None),
                    position  = getattr(p, "position", None),
                    slot      = getattr(p, "slot_position", None),
                    proj      = float(getattr(p, "projected_points", 0.0) or 0.0)
                )
                if s.slot in ("BE", "IR"):
                    bench.append(s)
                else:
                    starters.append(s)
    return starters, bench


FLEX_ELIGIBLE = {"RB", "WR", "TE"}

def eligible_for_slot(candidate_pos: str, slot: str) -> bool:
    if slot in {"RB","WR","QB","TE","K","D/ST"}:
        return candidate_pos == slot
    # ESPN has variants like "RB/WR/TE", treat as FLEX
    return (slot == "FLEX") or ("RB/WR/TE" in slot) or (slot == "W/R/T") and (candidate_pos in FLEX_ELIGIBLE)

# conservative baseline if no bench eligible (adjust for your league)
WAIVER_BASELINE = {"QB": 17.0, "RB": 10.0, "WR": 9.0, "TE": 7.0, "K": 7.0, "D/ST": 7.0}

def choose_replacement(bench: List[Starter], vacated_slot: str, waiver_pos: str) -> Starter:
    eligible = [b for b in bench if eligible_for_slot(b.position, vacated_slot)]
    if eligible:
        return max(eligible, key=lambda s: s.proj)
    # fallback: a dummy replacement with waiver baseline projection
    return Starter(player_id=-1, name=f"Waiver {waiver_pos}", position=waiver_pos, slot=vacated_slot, proj=WAIVER_BASELINE.get(waiver_pos, 7.0))


rng = np.random.default_rng(42)

def sample_points(mu: float, sigma: float, size: int) -> np.ndarray:
    # Truncated at zero (no negative weeks)
    draws = rng.normal(loc=mu, scale=sigma, size=size)
    return np.clip(draws, 0.0, None)

def simulate_win_probability(
    your_starters: List[Starter],
    opp_starters: List[Starter],
    pos_sigma: Dict[str, float],
    sims: int = 20000
) -> float:
    # Sum of independent normals per team
    you = np.zeros(sims, dtype=float)
    opp = np.zeros(sims, dtype=float)

    for s in your_starters:
        sigma = pos_sigma.get(s.position, 7.0)
        you += sample_points(s.proj, sigma, sims)

    for s in opp_starters:
        sigma = pos_sigma.get(s.position, 7.0)
        opp += sample_points(s.proj, sigma, sims)

    return float((you > opp).mean())

def wpa_for_player(
    league: League,
    week: int,
    your_team_id: int,
    opp_team_id: int,
    player_id: int,
    pos_sigma: Dict[str, float],
    sims: int = 20000
) -> Tuple[float, float, float]:
    """
    Returns: (win_pct_with_player, win_pct_with_replacement, WPA = diff)
    """
    your_starters, your_bench = get_lineup_for_week(league, your_team_id, week)
    opp_starters, _ = get_lineup_for_week(league, opp_team_id, week)

    # find target player in starters
    target = next((s for s in your_starters if s.player_id == player_id), None)
    if target is None:
        raise ValueError("Player is not in starting lineup for the selected week.")

    # Build the 'with player' lineup (as-is)
    with_player = list(your_starters)

    # Build the 'with replacement' lineup: remove target, add replacement
    replacement = choose_replacement(your_bench, vacated_slot=target.slot, waiver_pos=target.position)
    with_replacement = [s for s in your_starters if s.player_id != player_id] + [replacement]

    p_win_player = simulate_win_probability(with_player, opp_starters, pos_sigma, sims=sims)
    p_win_repl   = simulate_win_probability(with_replacement, opp_starters, pos_sigma, sims=sims)
    wpa          = p_win_player - p_win_repl
    return p_win_player, p_win_repl, wpa

def calculate_historical_wpa(weekly_df, matchups_df,
                             replacement_depth={"QB":12,"RB":24,"WR":36,"TE":12},
                             max_week=14):
    results = defaultdict(lambda: {"player_name": None, "position": None, "games_played": 0, "wins_added": 0})

    for (yr, wk), wk_df in weekly_df.groupby(["year", "week"]):
        if wk > max_week: continue

        # 1. replacement baselines
        repl_scores = {}
        for pos, depth in replacement_depth.items():
            pos_scores = wk_df.loc[(wk_df["position"] == pos) & (wk_df["is_starter"]), "points"]
            repl_scores[pos] = pos_scores.sort_values(ascending=False).iloc[depth-1] if len(pos_scores) >= depth else pos_scores.median()

        # 2. loop through matchups
        for _, row in matchups_df[(matchups_df["year"]==yr)&(matchups_df["week"]==wk)].iterrows():
            home_id, away_id = row.home_id, row.away_id
            home_score, away_score = row.home_score, row.away_score

            # players in this matchup
            home_players = wk_df[wk_df["team_id"]==home_id]
            away_players = wk_df[wk_df["team_id"]==away_id]

            # check each starter’s contribution
            for team_side, team_df, team_score, opp_score in [
                ("home", home_players, home_score, away_score),
                ("away", away_players, away_score, home_score)
            ]:
                for _, p in team_df[team_df["is_starter"]].iterrows():
                    pos = p["position"]
                    actual_pts = p["points"]
                    repl_pts   = repl_scores.get(pos, 0.0)
                    counterfactual_score = team_score - actual_pts + repl_pts

                    # did this player change the outcome?
                    win_actual = team_score > opp_score
                    win_counter = counterfactual_score > opp_score
                    delta = int(win_actual) - int(win_counter)  # 1 if player secured a win, -1 if cost a win

                    pid = p["player_id"]
                    results[pid]["player_name"] = p["player_name"]
                    results[pid]["position"] = pos
                    results[pid]["games_played"] += 1
                    results[pid]["wins_added"] += delta

    out = pd.DataFrame([
        {"player_id": pid,
         "player_name": vals["player_name"],
         "position": vals["position"],
         "games_played": vals["games_played"],
         "wins_added": vals["wins_added"]}
        for pid, vals in results.items()
    ])
    return out.sort_values("wins_added", ascending=False)



# (A) One-time historical pull (past seasons) to calibrate σ
hist = collect_weekly_points(years=[2024])  # add more if you want
pos_sigma = estimate_sigma_by_pos(hist)

# # (B) For a given week/team/opponent/player:
# WEEK = 3
# YOUR_TEAM_ID = 7
# OPP_TEAM_ID  = 4
# PLAYER_ID    = 123456  # the starter you’re evaluating

# p_with, p_repl, wpa = wpa_for_player(
#     league=league,
#     week=WEEK,
#     your_team_id=YOUR_TEAM_ID,
#     opp_team_id=OPP_TEAM_ID,
#     player_id=PLAYER_ID,
#     pos_sigma=pos_sigma,
#     sims=20000
# )

# print(f"Win% with player:       {p_with:.3f}")
# print(f"Win% with replacement:  {p_repl:.3f}")
# print(f"WPA (weekly):           {wpa:+.3f}")

In [167]:
import numpy as np
import pandas as pd
from typing import Dict, Tuple, Optional

# =========================================================
# 1) Data collection (unchanged, still returns weekly_df)
# =========================================================

def collect_weekly_points(years, max_week: int = 14) -> Tuple[pd.DataFrame, pd.DataFrame]:
    """
    Collects weekly player-level data and matchup-level data from ESPN box scores.
    You must implement get_league(year) to return an espn_api.League for that year.

    Returns:
      weekly_df   -> one row per player per week (includes starters & bench)
      matchups_df -> one row per matchup per week (kept for completeness; not used below)
    """
    rows = []
    matchups = []
    for yr in years:
        lg = get_league(yr)   # <-- define with your ESPN creds (league_id, swid, espn_s2)
        for wk in range(1, max_week + 1):
            for box in lg.box_scores(week=wk):
                # matchup info
                matchups.append({
                    "year": yr, "week": wk,
                    "home_id": box.home_team.team_id,
                    "away_id": box.away_team.team_id,
                    "home_score": box.home_score,
                    "away_score": box.away_score
                })
                # player info
                for side in ("home_lineup", "away_lineup"):
                    team_id = (box.home_team.team_id if side == "home_lineup"
                               else box.away_team.team_id)
                    for p in getattr(box, side, []) or []:
                        rows.append({
                            "year": yr,
                            "week": wk,
                            "team_id": team_id,
                            "player_id": getattr(p, "playerId", None),
                            "player_name": getattr(p, "name", None),
                            "position": getattr(p, "position", None),
                            "slot": getattr(p, "slot_position", None),  # e.g., "RB","WR","TE","W/R/T","FLEX"
                            "points": getattr(p, "points", None),
                            "is_starter": getattr(p, "slot_position", "") not in ("BE", "IR")
                        })
    return pd.DataFrame(rows), pd.DataFrame(matchups)


# =========================================================
# 2) Helpers for league config & demand
# =========================================================

DEFAULT_BASE_STARTERS = {"QB": 1, "RB": 2, "WR": 2, "TE": 1}
FLEX_SLOT_NAMES = {"FLEX", "W/R/T", "RB/WR/TE"}  # common ESPN labels

def infer_flex_shares_from_usage(weekly_df: pd.DataFrame) -> Dict[str, float]:
    """
    Empirically estimate what fraction of FLEX starts go to RB/WR/TE in your league.
    Looks only at rows where a starter's slot is a FLEX-type slot.
    """
    df = weekly_df.copy()
    df = df[df["is_starter"].fillna(False)]
    df = df[df["slot"].isin(FLEX_SLOT_NAMES)]
    counts = df["position"].value_counts()
    # Keep only eligible positions
    counts = counts[counts.index.isin(["RB", "WR", "TE"])]
    if counts.sum() == 0:
        # fallback to equal shares if we saw no FLEX usage
        return {"RB": 1/3, "WR": 1/3, "TE": 1/3}
    shares = (counts / counts.sum()).to_dict()
    # ensure all three keys exist
    for k in ["RB", "WR", "TE"]:
        shares.setdefault(k, 0.0)
    return shares

def compute_positional_demand_per_team(
    base_starters: Dict[str, float],
    flex_slots_per_team: float,
    flex_shares: Dict[str, float]
) -> Dict[str, float]:
    """
    Effective per-team slot demand by position: base + FLEX allocation.
    QB doesn't use FLEX, so demand==base. RB/WR/TE get FLEX share.
    """
    d = dict(base_starters)
    d["QB"] = base_starters.get("QB", 1)
    d["RB"] = base_starters.get("RB", 2) + flex_slots_per_team * flex_shares.get("RB", 0.0)
    d["WR"] = base_starters.get("WR", 2) + flex_slots_per_team * flex_shares.get("WR", 0.0)
    d["TE"] = base_starters.get("TE", 1) + flex_slots_per_team * flex_shares.get("TE", 0.0)
    return d


# =========================================================
# 3) Season-anchored benchmarks
# =========================================================

def compute_weekly_last_starter_thresholds(
    weekly_df: pd.DataFrame,
    team_count: int,
    demand_per_team: Dict[str, float],
    max_week: Optional[int] = None
) -> pd.DataFrame:
    """
    For each (year, week, position), compute the 'last starter' cutoff R_{pos,t}
    as the K-th highest started score, where K = round(team_count * demand_per_team[pos]).
    We cap K by the number of observed started players that week at that position.

    Returns a DataFrame: ["year","week","position","K","n_started","R_week"]
    """
    df = weekly_df.copy()
    df = df[df["is_starter"].fillna(False)]
    if max_week is not None:
        df = df[df["week"] <= max_week]

    # precompute K per position (constant across weeks)
    K_by_pos = {pos: max(1, int(round(team_count * demand_per_team[pos])))
                for pos in ["QB", "RB", "WR", "TE"]}

    out_rows = []
    for (yr, wk, pos), g in df.groupby(["year", "week", "position"]):
        # Only positions we care about
        if pos not in K_by_pos:
            continue
        scores = g["points"].dropna().sort_values(ascending=False)
        n = len(scores)
        K = min(K_by_pos[pos], n) if n > 0 else 0
        if K > 0:
            R_week = float(scores.iloc[K-1])
        else:
            R_week = np.nan
        out_rows.append({
            "year": yr, "week": wk, "position": pos,
            "K": K_by_pos[pos], "n_started": n, "R_week": R_week
        })
    return pd.DataFrame(out_rows)

def compute_season_replacement_thresholds(
    weekly_thresholds: pd.DataFrame
) -> pd.DataFrame:
    """
    Season replacement line per (year, position) as the median of weekly R_week values.
    Returns: ["year","position","R_season"]
    """
    return (weekly_thresholds
            .dropna(subset=["R_week"])
            .groupby(["year", "position"], as_index=False)["R_week"]
            .median()
            .rename(columns={"R_week": "R_season"}))

def add_season_positional_percentile(
    weekly_df: pd.DataFrame
) -> pd.DataFrame:
    """
    Adds SPP_season (0..1) for each row based on the empirical CDF of all STARTED
    weeks in that (year, position). Bench/IR rows are left NaN.
    """
    df = weekly_df.copy()
    mask = df["is_starter"].fillna(False)
    df["SPP_season"] = np.nan

    # Rank within (year, position) across started weeks only
    df.loc[mask, "SPP_season"] = (
        df[mask]
        .groupby(["year", "position"])["points"]
        .rank(pct=True, method="average")
        .values
    )
    return df


# =========================================================
# 4) Per-week season-anchored values (PAR_season, PVW)
# =========================================================

def compute_week_values_season_anchored(
    weekly_df: pd.DataFrame,
    team_count: int,
    base_starters: Dict[str, float] = DEFAULT_BASE_STARTERS,
    flex_slots_per_team: float = 1.0,
    flex_shares: Optional[Dict[str, float]] = None,
    lambda_points: float = 3.0,
    max_week: Optional[int] = 14
) -> pd.DataFrame:
    """
    Main entry: returns one row per STARTED player-week with season-anchored metrics.

    Outputs columns:
      ["year","week","team_id","player_id","player_name","position","points",
       "R_season","PAR_season","SPP_season","PVW"]

    Where:
      PAR_season = points - R_season(position,year)
      PVW        = PAR_season + lambda_points * (SPP_season - 0.5)
    """
    df = weekly_df.copy()

    # Keep only starters (we value starting weeks)
    df = df[df["is_starter"].fillna(False)]
    if max_week is not None:
        df = df[df["week"] <= max_week]

    # FLEX shares: passed or inferred from empirical usage
    if flex_shares is None:
        flex_shares = infer_flex_shares_from_usage(weekly_df)

    # Effective per-team demand by position
    demand_per_team = compute_positional_demand_per_team(
        base_starters=base_starters,
        flex_slots_per_team=flex_slots_per_team,
        flex_shares=flex_shares
    )

    # Weekly last-starter thresholds -> then season medians per (year, position)
    weekly_R = compute_weekly_last_starter_thresholds(
        weekly_df=weekly_df,
        team_count=team_count,
        demand_per_team=demand_per_team,
        max_week=max_week
    )
    season_R = compute_season_replacement_thresholds(weekly_R)  # ["year","position","R_season"]

    # Add season positional percentile (SPP) for started weeks
    df = add_season_positional_percentile(df)

    # Merge in R_season per (year, position)
    df = df.merge(season_R, on=["year", "position"], how="left")

    # Compute PAR_season and PVW
    df["PAR_season"] = df["points"] - df["R_season"]
    # Center SPP around 0: (SPP - 0.5); if SPP is NaN (shouldn't be for starters), treat as 0
    spp_centered = (df["SPP_season"].fillna(0.5) - 0.5)
    df["PVW"] = df["PAR_season"] + lambda_points * spp_centered

    # Select tidy output
    out_cols = ["year","week","team_id","player_id","player_name","position","points",
                "R_season","PAR_season","SPP_season","PVW"]
    return df[out_cols].sort_values(["year","week","position","PVW"], ascending=[True,True,True,False])


# =========================================================
# 5) Example usage
# =========================================================

# 1) Pull 2024 data (weeks 1-14 by default)
weekly_df, _matchups_df = collect_weekly_points([2024], max_week=14)

# 2) Compute season-anchored weekly values for a 12-team league, 1 FLEX
week_values = compute_week_values_season_anchored(
    weekly_df=weekly_df,
    team_count=12,
    base_starters={"QB":1,"RB":2,"WR":2,"TE":1},
    flex_slots_per_team=1.0,
    # Option A: force equal FLEX shares (as you suggested):
    # flex_shares={"RB": 1/3, "WR": 1/3, "TE": 1/3},
    # Option B: infer from actual usage (default if None):
    flex_shares=None,
    lambda_points=1.0,
    max_week=14
)

# 3) Inspect
# print(week_values.head(12))

# Optional: aggregate by player to see season summary (still season-anchored metrics)
season_summary = (week_values
    .groupby(["player_id","player_name","position"], as_index=False)
    .agg(weeks_started=("week","count"),
            pvw_sum=("PVW","sum"),
            par_sum=("PAR_season","sum"),
            pvw_mean=("PVW","mean"),
            spp_mean=("SPP_season","mean"))
    .sort_values(["pvw_sum"], ascending=False)
)
# print(season_summary.head(12))

In [168]:
season_summary.head(20)

,player_id,player_name,position,weeks_started,pvw_sum,par_sum,pvw_mean,spp_mean
177,4362628,Ja'Marr Chase,WR,13,320.381278,317.40,24.644714,0.729329
103,3916387,Lamar Jackson,QB,13,304.131071,301.14,23.394698,0.730082
109,3918298,Josh Allen,QB,13,273.050476,271.36,21.003883,0.630037
111,3929630,Saquon Barkley,RB,13,261.526440,259.05,20.117418,0.690495
127,4040715,Jalen Hurts,QB,13,237.508690,236.22,18.269899,0.599130
157,4262921,Justin Jefferson,WR,13,237.502687,235.18,18.269437,0.678668
186,4374302,Amon-Ra St. Brown,WR,13,229.865022,228.18,17.681925,0.629617
137,4241389,CeeDee Lamb,WR,13,220.686564,219.30,16.975890,0.606659
62,3043078,Derrick Henry,RB,13,215.185864,213.25,16.552759,0.648913
101,3915511,Joe Burrow,QB,10,211.142143,209.66,21.114214,0.648214
72,3054850,Alvin Kamara,RB,13,208.963874,207.35,16.074144,0.624144
213,4430807,Bijan Robinson,RB,13,207.961257,205.85,15.997020,0.662404
224,4569618,Garrett Wilson,WR,13,199.889427,199.20,15.376110,0.553033
194,4426502,Drake London,WR,13,198.070925,197.30,15.236225,0.559302
209,4429795,Jahmyr Gibbs,RB,13,197.690314,195.85,15.206947,0.641563
204,4429160,De'Von Achane,RB,13,191.727487,190.45,14.748268,0.598268
190,4426348,Jayden Daniels,QB,12,191.720119,191.36,15.976677,0.530010
129,4047365,Josh Jacobs,RB,13,188.732199,187.35,14.517861,0.606323
70,3052587,Baker Mayfield,QB,9,183.759643,182.34,20.417738,0.657738
212,4430737,Kyren Williams,RB,13,183.003141,181.85,14.077165,0.588703

=== 2020 ===
Max week: 16
Week 1: The “Mecca” Daddy satty
Week 2: The “Mecca” Daddy satty
Week 3: The “Mecca” Daddy satty
Week 4: The “Mecca” Daddy satty
Week 5: The “Mecca” Daddy satty
Week 6: The “Mecca” Daddy satty
Week 7: The “Mecca” Daddy satty
Week 8: Big Daddy Bones
Week 9: Big Daddy Bones
Week 10: Big Daddy Bones
Week 11: mimi top gavin bottom
Week 12: Greasy  Anal
Week 13: Greasy  Anal
Week 14: Greasy  Anal
Week 15: Greasy  Anal
Week 16: Greasy  Anal

=== 2021 ===
Max week: 17
Week 1: Monica  Lazynski
Week 2: Monica  Lazynski
Week 3: Monica  Lazynski
Week 4: Monica  Lazynski
Week 5: Monica  Lazynski
Week 6: Monica  Lazynski
Week 7: Monica  Lazynski
Week 8: Monica  Lazynski
Week 9: Monica  Lazynski
Week 10: Monica  Lazynski
Week 11: Monica  Lazynski
Week 12: Monica  Lazynski
Week 13: Monica  Lazynski
Week 14: Monica  Lazynski
Week 15: Monica  Lazynski
Week 16: Monica  Lazynski
Week 17: Monica  Lazynski

=== 2022 ===
Max week: 17
Week 1: Brxggzy Bunch
Week 2: Big  Booty Squad
Week 3: Big  Booty Squad
Week 4: Big  Booty Squad
Week 5: Big  Booty Squad
Week 6: Big  Booty Squad
Week 7: Big  Booty Squad
Week 8: Big  Booty Squad
Week 9: The “Mecca” Daddy satty
Week 10: The “Mecca” Daddy satty
Week 11: The “Mecca” Daddy satty
Week 12: The “Mecca” Daddy satty
Week 13: The “Mecca” Daddy satty
Week 14: The “Mecca” Daddy satty
Week 15: The “Mecca” Daddy satty
Week 16: The “Mecca” Daddy satty
Week 17: The “Mecca” Daddy satty

=== 2024 ===
Max week: 17
Week 1: Team Brenner
Week 2: Team Brenner
Week 3: Team Brenner
Week 4: Team Brenner
Week 5: Team Brenner
Week 6: Team Brenner
Week 7: Team Brenner
Week 8: Team Brenner
Week 9: Team Brenner
Week 10: Team Brenner
Week 11: Team Brenner
Week 12: Team Brenner
Week 13: Team Brenner
Week 14: Team Brenner
Week 15: Team Brenner
Week 16: Team Brenner
Week 17: Team Brenner